config/routes.rb
Rails.application.routes.draw do
  root 'application#welcome'

  resources :users, only: [:new, :create, :edit, :update, :destroy]
  get 'profile', to: 'users#show', as: 'profile'
  get 'request-admin', to: 'users#request_admin', as: 'request_admin'
  scope :users do
    resources :reports
  end
  resources :congregations
  resources :sessions, only: [:new, :create]
  delete 'sessions', to: 'sessions#destroy', as: 'session'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/congregation.rb
class Congregation < ApplicationRecord
  has_many :users
  has_many :reports, through: :users

  def name_with_city_state
    "#{self.name} - #{self.city}, #{self.state}"
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :congregation, optional: true
  has_many :reports

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_if_not_logged_in
  skip_before_action :redirect_if_not_logged_in, only: [:welcome]

  def welcome
    
  end

  private

  def logged_in?
    !!session[:user_id]
  end

  def redirect_if_not_logged_in
    return redirect_to new_session_path, alert: "You must be logged in" if !logged_in?
  end

  def redirect_if_logged_in
    return redirect_to user_path(current_user), alert: "You are already logged in" if logged_in?
  end

  def current_user
    @user = User.find_by(id: session[:user_id]) if logged_in?
  end
end

app/controllers/congregations_controller.rb
class CongregationsController < ApplicationController
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    @reports = current_user.reports
  end

  def new
    
  end

  def show
    @report = current_user.reports.find_by(id: params[:id])
    redirect_to reports_path if !@report
  end

  def create
    current_user.reports.create(report_params)
    redirect_to reports_path
  end

  private

  def report_params
    params.require(:report).permit(:month, :year, :placements, :video_showings, :hours, :return_visits, :bible_studies, :comments)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :redirect_if_not_logged_in, only: [:new, :create]

  def create
    @user = User.find_by(email: params[:user][:email].downcase)
    @user = @user.try(:authenticate, params[:user][:password])
    return redirect_to new_session_path, alert: "Unable to sign in" unless @user

    session[:user_id] = @user.id
    redirect_to profile_path(@user), notice: "Welcome #{@user.first_name}!"
  end

  def destroy
    session.delete :user_id
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :redirect_if_not_logged_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.errors.any?
      @errors = @user.errors.full_messages.join(", ")
      render :new
    end
    session[:user_id] = @user.id
    redirect_to profile_path, notice: "Welcome #{@user.first_name}! Account successfully created"
  end

  def update
    @user = User.find(current_user.id)
    @user.update(user_params)
    redirect_to profile_path, notice: "Account successfully updated!"
  end

  def request_admin
  
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :telephone, :email, :password, :password_confirmation, :congregation_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/congregations_helper.rb
module CongregationsHelper

  def current_user_congregation
    if current_user.congregation
      render partial: 'congregations/cong_show'
    else
      render partial: 'congregations/list', locals: {user: current_user}
    end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper

  def report_month_year(report)
    "#{report.month} - #{report.year}"
  end

  def report_months_for_select
    %w[January
      February
      March
      April
      May
      June
      July
      August
      September
      October
      November
      December]
  end

  def report_years_for_select
    [2018, 2019, 2020]
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/views/congregations/_cong_show.html.erb
<%= current_user.congregation.name_with_city_state %>
<h4>Are you an administrator for this congregation?</h4>
<button><%= link_to  "Request Admin Access", request_admin_path %></button>

app/views/congregations/_list.html.erb
<p>Select Congregation</p>
<%= form_for(user) do |f| %>
  <%= f.collection_select :congregation_id, Congregation.all, :id, :name_with_city_state %>
  <%= f.submit "Assign Congregation" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Keep My Time" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Keep My Time</li>
          <li><%= link_to  "New Report", new_report_path %></li>
          <li><%= link_to  "My Reports", reports_path %></li>
          
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><input type="search" placeholder="Search"></li>
          <li><button type="button" class="button">Search</button></li>
          <li><%= link_to "Profile", profile_path %></li>
        </ul>
      </div>
    </div>

    <% flash.each do |name, msg| %>
      <% if name == "notice" %>
        <div class="alert alert-success alert-dismissible fade show">
          <p><%= msg %></p>
      <% else %>
        <div class="alert alert-danger alert-dismissible fade show">
          <p><%= msg %></p>
      <% end %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/reports/index.html.erb
<ul>
  <% @reports.each do |report| %>
      <li><%= link_to report_month_year(report), report_path(report) %></li>
  <% end %>
</ul>

app/views/reports/new.html.erb
<h2>New Field Service Report</h2>

<%= form_for(:report, url: reports_path) do |f| %>

  <%= f.hidden_field :user_id %>

  <div class="field">
    <%= f.label :month %><br />
    <%= f.select :month, report_months_for_select, {:include_blank => "Select Month"}, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.select :year, report_years_for_select, {:include_blank => "Select Year"},autofocus: false %>
  </div>

  <div class="field">
    <%= f.label :placements %><br />
    <%= f.number_field :placements, value: 0, within: 0..100, autofocus: false %>
  </div>

  <div class="field">
    <%= f.label :video_showings %><br />
    <%= f.number_field :video_showings, value: 0, within: 0..100, autofocus: false %>
  </div>

  <div class="field">
    <%= f.label :hours %><br />
    <%= f.number_field :hours, value: 0, within: 0..200, autofocus: false %>
  </div>

  <div class="field">
    <%= f.label :return_visits %><br />
    <%= f.number_field :return_visits, value: 0, within: 0..100, autofocus: false %>
  </div>

  <div class="field">
    <%= f.label :bible_studies %><br />
    <%= f.number_field :bible_studies, value: 0, within: 0..30, autofocus: false %>
  </div>

  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments, autofocus: false %>
  </div>

  <div class="actions">
    <%= f.submit "Save Report" %>
  </div>
<% end %>

app/views/reports/show.html.erb
<h2><%= @report.month %> <%= @report.year %></h2>

<%= form_for(@report, url: reports_path) do |f| %>

  <div class="field">
    <%= f.label :placements %><br />
    <%= f.number_field :placements  %>
  </div>

  <div class="field">
    <%= f.label :video_showings %><br />
    <%= f.number_field :video_showings %>
  </div>

  <div class="field">
    <%= f.label :hours %><br />
    <%= f.number_field :hours %>
  </div>

  <div class="field">
    <%= f.label :return_visits %><br />
    <%= f.number_field :return_visits %>
  </div>

  <div class="field">
    <%= f.label :bible_studies %><br />
    <%= f.number_field :bible_studies %>
  </div>

  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments  %>
  </div>

  <div class="actions">
    <%= f.submit "Update Report", disabled: true %>
  </div>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for(@user, url: users_path) do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "given-name" %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: false, autocomplete: "family-name" %>
  </div>

  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.telephone_field :telephone, autofocus: false, autocomplete: "tel-national" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: false, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/request_admin.html.erb
<h2>Request Administration Access</h2>

app/views/users/show.html.erb
  <h2>User Profile</h2>

  <%= form_for(current_user, url: user_path(current_user)) do |f| %>

        <div class="row">
          <div class="small-12 medium-6 columns">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, autofocus: false, autocomplete: "given-name" %>
          </div>
        
          <div class="small-12 medium-6 columns">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, autofocus: false, autocomplete: "family-name" %>
          </div>
        </div>

        <div class="row">
          <div class="small-12 medium-6 columns">
            <%= f.label :telephone %>
            <%= f.telephone_field :telephone, autofocus: false, autocomplete: "tel-national" %>
          </div>
        </div>

        <div class="row">
          <div class="small-12 medium-6 columns">
            <%= f.label :email %>
            <%= f.email_field :email, autofocus: false, autocomplete: "email" %>
          </div>
        </div>

        <div class="row">
          <div class="small-12 medium-6 columns">
            <%= f.submit "Update Account" %>
          </div>
        </div>
        
  <% end %>

<div>
  <h2>Congregation</h2>
  <p><%= current_user_congregation %></p>
</div>

<%= link_to "Log Out", session_path, method: :delete %>